#!/bin/bash

echo "🔑 Adding OpenAI API Key to Vercel Environment Variables"
echo ""
echo "You need to add the OPENAI_API_KEY to your Vercel project."
echo ""
echo "📋 Steps:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click on your 'the-ai-lab-eight' project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add new environment variable:"
echo "   - Name: OPENAI_API_KEY"
echo "   - Value: [Your OpenAI API key from platform.openai.com]"
echo "   - Environment: Production, Preview, Development (select all)"
echo "5. Click 'Save'"
echo "6. Redeploy the project"
echo ""
echo "🔗 Quick links:"
echo "- Vercel Dashboard: https://vercel.com/dashboard"
echo "- OpenAI API Keys: https://platform.openai.com/api-keys"
echo ""
echo "💡 After adding the key, run: git push"
echo "   This will trigger a new deployment with the environment variable."